version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run: echo 'export PATH=/home/circleci/.local/bin:${PATH}' >> ${BASH_ENV}
      - checkout

      - run:
          name: install pip
          command: |
            pip install --user -r requirements.txt
            pip install --user -r test_requirements.txt
      - run:
          command: |
            flake8
            # pytest -vv
